version: '3.3'
services:
  flask:
    build: .
    image: flask_server:latest
    command: bash -c "python main.py"
    env_file:
      - envs/.env
    environment:
      - FLASK_DEBUG=True
      - FLASK_SERVER_HOST=0.0.0.0
      - FLASK_SERVER_PORT=5000
    ports:
      - "8000:5000"
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/main.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../ssl:/etc/ssl
    depends_on:
      - flask